'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'public', 'index.html'), 'utf8');
const js = fs.readFileSync(path.join(root, 'public', 'client.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'public', 'app.css'), 'utf8');
assert.match(html, /window\.SIM_BASE/);
assert.match(html, /simplus\\d\+/, 'Sim+ alias must retain its path prefix for assets and APIs');
assert.ok(html.includes("window.SIM_BASE + '/client.js"));
assert.match(js, /id="question"/);
assert.match(js, /id="root"/);
assert.match(js, /id="root"[^>]*minlength="15"/);
assert.match(js, /id="j-\$\{r\.id\}"[^>]*minlength="15"/);
assert.match(js, /meaningful characters/);
assert.match(js, /form\.requestSubmit\(\)/);
assert.match(js, /partial chart/i);
assert.match(js, /Observation window/i);
assert.match(js, /Question starters/);
assert.match(js, /data-starter/);
assert.match(js, /Suggestions update as you ask/);
assert.match(js, /filter\(q=>!asked\.has\(clean\(q\)\)\)\.slice\(0,5\)/);
assert.match(css, /\.question-starters/);
assert.match(css, /\.starter/);
assert.doesNotMatch(css, /pointer-events\s*:\s*none[^}]*textarea/i);
assert.match(css, /caret-color:var\(--amber\)/);
assert.match(js, /data-phase=/, 'phase navigation must render real controls');
assert.match(js, /bindPhaseNav/, 'phase controls must be wired to navigation');
assert.match(js, /renderCompletedInterview/, 'completed interviews must remain reviewable without reopening them');
assert.match(js, /captureReportDraft/);
assert.match(js, /restoreReportDraft/);
assert.match(js, /id="preview-run"/, 'observation must expose Preview run');
assert.match(js, /startObservationPreview/);
assert.match(css, /\.phase\{[^}]*cursor:pointer/, 'enabled phase controls must look clickable');
assert.match(css, /\.phase:disabled\{[^}]*cursor:not-allowed/);
assert.match(css, /\.observation-preview/);
assert.match(js, /OBSERVATION_CLAIMS/);
assert.match(js, /id="preview-desk"/, 'Preview run must render the observed claim activity');
assert.match(js, /previewSheet/);
assert.match(js, /Reshuffle members/, 'Interview panel must expose legal-order reshuffling');
assert.match(js, /pendingOrder/);
assert.match(css, /\.claim-sheet/);
assert.match(css, /\.appointment-plan/);
console.log('client contract: passed');
