'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'public', 'index.html'), 'utf8');
const js = fs.readFileSync(path.join(root, 'public', 'client.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'public', 'app.css'), 'utf8');
assert.match(html, /window\.SIM_BASE/);
assert.match(html, /simplus\\d\+/, 'Sim+ alias must retain its path prefix for assets and APIs');
assert.ok(html.includes("window.SIM_BASE + '/client.js"));
assert.match(js, /id="question"/);
assert.match(js, /id="root"/);
assert.match(js, /id="root"[^>]*minlength="15"/);
assert.match(js, /id="j-\$\{r\.id\}"[^>]*minlength="15"/);
assert.match(js, /meaningful characters/);
assert.match(js, /form\.requestSubmit\(\)/);
assert.match(js, /partial chart/i);
assert.match(js, /Observation window/i);
assert.match(js, /Question starters/);
assert.match(js, /data-starter/);
assert.match(js, /Suggestions update as you ask/);
assert.match(js, /filter\(q=>!asked\.has\(clean\(q\)\)\)\.slice\(0,5\)/);
assert.match(css, /\.question-starters/);
assert.match(css, /\.starter/);
assert.doesNotMatch(css, /pointer-events\s*:\s*none[^}]*textarea/i);
assert.match(css, /caret-color:var\(--amber\)/);
console.log('client contract: passed');
