const assert=require('assert');
const fs=require('fs');
const path=require('path');
const S=require('../lib/scenario.js');
const {buildClosingLesson}=require('../lib/closingLesson.js');
const cfg=S.publicConfig();
const packet=JSON.stringify(cfg.briefing);
for(const forbidden of ['Tuesday','eighty minutes','semester','your team runs Midland']) assert.equal(packet.toLowerCase().includes(forbidden.toLowerCase()),false,forbidden);
for(const name of ['Dale Brenner','Renata Oyelaran','Tom Vasquez','Sam Achterberg']) assert.ok(packet.includes(name),name);
assert.ok(packet.includes('thirty minutes')&&packet.includes('two annual $9 million allocations')&&packet.includes('third year'));
assert.ok(packet.includes('Nineteen percent of our visits find nothing wrong')&&packet.includes('$290'));
assert.equal(cfg.meta.minutes,30);
assert.ok(cfg.position.includes('Run has a $3M minimum')&&cfg.position.includes('Features each have a $3M annual ceiling'));
assert.equal(cfg.reflectionPrompts[0],'Which of Dale, Renata, Tom, or Sam did you overrule most?');
assert.ok(cfg.reflectionFollowups[0].includes('After seeing Year 3'));
const y1={run:3,uptime:2,capacity:2,connect:0,features:2};
const y1o=S.evaluateYear1(y1);
assert.equal(y1o.band,'weak');assert.ok(y1o.allocationNotes.some(x=>x.includes('Connect was $0M')));assert.ok(y1o.allocationNotes.some(x=>x.includes('$6.1M Run bill')));
const heatA={run:3,uptime:3,capacity:0,connect:3,features:0},heatB={run:3,uptime:3,capacity:0,connect:3,features:0};
const heat=S.evaluateYear2(heatA,heatB).heat;assert.equal(heat.band,'strong');assert.ok(heat.allocationNotes.some(x=>x.includes('Cumulative Uptime was $6M')&&x.includes('$3M sat above that line')));
for(const band of ['strong','data_no_room','pilot','weak']){
  const copy={strong:S.evaluateYear3({run:3,uptime:1,capacity:1,connect:3,features:1},{run:3,uptime:2,capacity:1,connect:2,features:1}),data_no_room:S.evaluateYear3({run:3,uptime:3,capacity:0,connect:3,features:0},{run:3,uptime:0,capacity:0,connect:3,features:3}),pilot:S.evaluateYear3({run:3,uptime:2,capacity:1,connect:2,features:1},{run:3,uptime:1,capacity:1,connect:1,features:3}),weak:S.evaluateYear3({run:3,uptime:2,capacity:1,connect:1,features:2},{run:3,uptime:2,capacity:1,connect:1,features:2})}[band];
  assert.ok(copy.narrative.includes('Tom:')&&copy.narrative.includes('Sam:'),band);
}
const weakComp=S.evaluateYear2({run:3,uptime:0,capacity:3,connect:0,features:3},{run:3,uptime:1,capacity:3,connect:1,features:1}).competitor.narrative;
assert.equal(weakComp.includes('market question arrived after the architecture decision'),false);assert.equal(weakComp.includes('we decided this before we knew'),false);
const buyers=S.evaluateBuyers({run:3,uptime:2,capacity:1,connect:1,features:2},{run:3,uptime:2,capacity:1,connect:1,features:2});
assert.ok(buyers.carrolton.roomLink.includes('No one in the room'));assert.ok(S.evaluateBuyers({run:3,uptime:2,capacity:1,connect:2,features:1},{run:3,uptime:2,capacity:1,connect:2,features:1}).ridge_hollow.reason.includes('After closing'));
assert.equal(new Set(Object.values(['strong','middle','weak'].reduce((o,b)=>(o[b]=S.evaluateYear1(b==='strong'?{run:3,uptime:1,capacity:1,connect:2,features:2}:b==='middle'?{run:3,uptime:2,capacity:1,connect:1,features:2}:{run:3,uptime:2,capacity:2,connect:0,features:2}).year2Intro,o),{}))).size,3);
const html=fs.readFileSync(path.join(__dirname,'..','public','index.html'),'utf8');
for(const marker of ['Pre-session briefing','What happens in the simulation','No one in the room speaks for this line.','year2-history','No Year 3 allocation','reflection-followup','align-self:start','The decisions are over. Explain what you would defend or change.']) assert.ok(html.includes(marker),marker);
for(const forbidden of ['What happens Tuesday','briefing packet your instructor posted before class','The architecture underneath it is the one built over the previous two years.']) assert.equal(html.includes(forbidden),false,forbidden);
const y1fn=html.slice(html.indexOf('function renderYear1Outcome'),html.indexOf('function renderYear2Events'));
assert.ok(y1fn.indexOf('<div class="outcome">')<y1fn.indexOf("runningHTML(S.year1"));
const y2fn=html.slice(html.indexOf('function renderYear2Events'),html.indexOf('function renderYear3'));
assert.ok(y2fn.indexOf('<div class="events"')<y2fn.indexOf("runningHTML(cum"));
assert.equal(html.includes('<div class="constraint">${esc(l.description'),false);
assert.equal(html.includes('<div class="alloc-rule">'),false);
const lesson=buildClosingLesson({run:3,uptime:3,capacity:3,connect:0,features:0},{run:3,uptime:3,capacity:3,connect:0,features:0},S.evaluateAll({run:3,uptime:3,capacity:3,connect:0,features:0},{run:3,uptime:3,capacity:3,connect:0,features:0}),S.DEFAULT_THRESHOLDS);
assert.equal((lesson.yourRun.join(' ').match(/Closest counterfactual:/g)||[]).length,1);assert.ok(lesson.yourRun.some(x=>x.includes('Renata')&&x.includes('Sam')));
console.log('RapidSim 03 Increment 3 checks passed.');
